Project popup
Tobby8629/Tobby-portfolio pull request #13
Opened 2022-12-22 14:29 UTC by Tobby8629

Built the project pop-up making use of:

- css position
- Javascript Dom manipulation
- Javascript forEach method

2022-12-22 15:46 UTC, GzimAsani requested changes
### Hello  @Tobby8629                               :wave:   
 Good job so far! There are some issues that you still need to work on to go to the next project but you are almost there!
 
 ## Highlights
 * Good job with your javascript:+1: 

 ## Required Changes 

- [ ] Check the comments below :arrow_double_down: 



 ## Optional suggestions
 _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding! clapclapclap
 
 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
 
 **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
 
 _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-22 15:46 UTC, GzimAsani commented on style.css
> +.popup {
- [ ] KIndly check the requirements on the image
Yours:
![image](https://user-images.githubusercontent.com/62705947/209170557-fb8aaea4-d30c-47e2-8abf-2a43dd0e5e07.png)
Design:
![image](https://user-images.githubusercontent.com/62705947/209170662-1fb2db56-b6d5-4f13-94c4-432bc3b7d4c1.png)
- PS: Same requirements go for mobile version as well

2022-12-22 18:25 UTC, huseyinbiyik requested changes
Hi @Tobby8629,

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet.
![tenor](https://user-images.githubusercontent.com/25887253/205415161-00e79d1b-af68-4f10-9b2c-265f460dc5da.gif)

 ## Highlights
- Linter checks passes 🟢
- Popup content generated dynamically with JavaScript 👌


 ## Required Changes ♻️
_Check the comments under the review._



_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-22 18:25 UTC, huseyinbiyik commented on style.css
> +.popup {
Kindly stick to the design as the previous reviewer requested. One of the main goals of this project is to implement the provided design.
Please check the spacing/margin/padding around the popup on the Figma design:
<img width="428" alt="Screenshot 2022-12-22 at 9 13 58 PM" src="https://user-images.githubusercontent.com/25887253/209200324-24a88a76-10b1-463b-ae46-95ffd8583e4c.png">

This one is yours. Still doesn't match the requirements.
<img width="1440" alt="Screenshot 2022-12-22 at 9 17 46 PM" src="https://user-images.githubusercontent.com/25887253/209200939-57bda7b8-9890-4e26-b0d1-6ed476a07e1a.png">

2022-12-23 00:52 UTC, Omar-Muhamad approved these changes
# Approved ✔
### Hi @Tobby8629 

Great job, Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![thumbs-up-agree](https://user-images.githubusercontent.com/68796232/158491866-20000001-88c2-4735-bb47-1ff65c7a44db.gif)


## (Highlights) Good Points: :+1:
- You documented your work professionally. ✔
- You used the correct workflow.  ✔
- All linters checks are ok. ✔

## (Changes Required) Aspects to improve: ♻️

- N/A

## [Optional] suggestions:

- N/A

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-12-23 01:00 UTC, merged